version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers

    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer/cache
      - run: php -d memory_limit=2G ./vendor/bin/phpunit
      - run: php -n -d memory_limit=2G ./vendor/bin/php-cs-fixer fix --verbose --diff --diff-format=udiff --dry-run
